### ISSUE TITLE
А если вот так?

### ISSUE THREAD

**Issue by mayorovp** [DarkByte2015/CoursedWork_v5#2]
Вот что я придумал. Надо вывернуть алгоритм наизнанку, организовав очередь клиентов вместо очереди задач. Это решит проблему правильного подключения клиентов в процессе работы - и одновременно очень сильно упростит код.

Вот пакет, который понадобится: https://www.nuget.org/packages/AsyncCollections/

Вот так должна выглядеть очередь: 

    AsyncQueue<ClientViewModel> clientsQueue = new AsyncQueue<ClientViewModel>();

Когда клиент подключается - мы его кладем в эту очередь:

        private async void ClientConnected(object sender, ClientChangeStateEventArgs e)
        {
            var client = new ClientViewModel(e.Callback, e.Address);
            client.ClientAborted += ClientAborted;
            Clients.Add(client);
            clientsQueue.Add(client);
        }

При удалении клиента его из очереди так просто не удалить - но нам это не важно.

        private void RemoveClient(ClientViewModel client)
        {
            Clients.Remove(client);
        }

Отмечу, что никакого управления задачами напрямую не происходит.

Теперь как задачи раздавать клиентам. Все очень просто. Сначала надо получить клиента из очереди:

        var client = await clientsQueue.TakeAsync();

Потом выдаем ему задачу, если не получилось - повторяем. По окончании задачи возвращаем клиента в очередь. И так надо сделать для каждой задачи.

Итого получается примерно так:

        var tasks = ClientJob.Distribute(BottomValue, TopValue, 1.0).Select(async job => {
           while (true) {
               var client = await clientsQueue.TakeAsync();
               try {
                   var result = await client.TryCalculate(job);
                   if (result.IsSuccess) {
                     clientsQueue.Add(client);
                     return result;
                   }
               } catch {
                   Clients.Remove(client);
               }
           }
        }).ToList();

Теперь можно эти результаты обработать:

        var done = 0;
        var tasks2 = tasks.Select(async result => {
          await result;
          done++;

          ProgressValue = (++done) * 100 / tasks.Count;
          TimeLost = result.Duration * (tasks.Count - done);
          return result.Result;
        }).ToList();
        ResultValue = (await Task.WhenAll(tasks2)).Sum();

**Comment by mayorovp** [comment]
Если не понятно что происходит вот в этой строчке: `.Select(async job => {` - поясняю.

Внутри Select - асинхронная лямбда. Она эквивалентна вот такой функции:

    async Task<CalculateReturnValue> Calculate(ClientJob job) {
       while (true) {
           var client = await clientsQueue.TakeAsync();
           try {
               var result = await client.TryCalculate(job);
               if (result.IsSuccess) {
                 clientsQueue.Add(client);
                 return result;
               }
           } catch {
               Clients.Remove(client);
           }
       }
    }

Метод Select применяется к этой лямбде самым обычным образом:
    
    var tasks = ClientJob.Distribute(BottomValue, TopValue, 1.0).Select(job => Calculate(job)).ToList();

Т.е. сразу никакого ожидания не происходит, все джобы начинают обрабатываются одновременно (ну, не совсем одновременно - все-таки программа-то однопоточная).

**Comment by DarkByte2015** [comment]
Уже не суть я все решил. Просидел сегодня до полчетвертого, но все таки все заработало. Сделал по простому через цикл который ждет пока количество результатов не станет равно изначальному количеству задач как у меня было раньше. Только добавил как вы тогда на форуме советовали задержку небольшую чтобы сильно не грузить. А TaskCompletionSource убрал. Хз может его и можно было применить как то, но ночью уже мозги не варили совсем так что забил на него. 

```
private async void Solve(object param)
{
	if (TopValue <= BottomValue || (TopValue - BottomValue) < StepValue ||
		BottomValue < 0 || TopValue < 0 || StepValue < 0)
	{
		ErrorThrown?.Invoke(new ArgumentException());
		return;
	}

	IsWorking = true;
	TimeLost = 0;
	ResultValue = null;
	
	foreach (var job in ClientJob.Distribute(BottomValue, TopValue, 1.0))
	{
		job.Step = StepValue;
		Jobs.Enqueue(job);
	}

	JobCount = Jobs.Count;
	await Task.WhenAll(Clients.Select(client => Calculate(client)));

	while (Results.Count != JobCount)
		await Task.Delay(100);

	ResultValue = Results.Sum();
	Jobs.Clear();
	Results.Clear();
	IsWorking = false;
}
```

**Comment by mayorovp** [comment]
Э...

Вы все-таки зря `await Task.WhenAll(Clients.Select(client => Calculate(client)));` использовали. Я же писал, что этот способ не "ловит" подключения клиентов во время работы.

TaskCompletionSource не виноват в том что вы его не использовали :)

Лучше верните его использование, замените ту строчку обратно на цикл и просто забейте на предупреждение студии. Я же правильно понимаю, что когда у вас было написано 

    foreach (var client in Clients)
        Calculate(client);

- все работало, и единственной проблемой было зеленое подчеркивание?

**Comment by mayorovp** [comment]
А когда будет свободное время - все-таки попробуйте вариант с очередью клиентов.

**Comment by DarkByte2015** [comment]
> Я же писал, что этот способ не "ловит" подключения клиентов во время работы.

Я же не зря в ClientConnected дописал
```
if (IsWorking)
        await CalculateAsync(client);
```

**Comment by DarkByte2015** [comment]
> все работало, и единственной проблемой было зеленое подчеркивание?

Честно скажу уже не помню, а проверять влом. Я уже пз сделал и сегодня иду сдавать.

**Comment by mayorovp** [comment]
Да, но проблема в том что Solve не ждет такого клиента при использовании `await Task.WhenAll(Clients.Select(...`

**Comment by DarkByte2015** [comment]
> Да, но проблема в том что Solve не ждет такого клиента при использовании await Task.WhenAll(Clients.Select(...

Не ждет, зато цикл ждет.

**Comment by mayorovp** [comment]
Старый вариант (с await DoneEvent.Task, кажется) тоже ждал.

**Comment by DarkByte2015** [comment]
> Старый вариант (с await DoneEvent.Task, кажется) тоже ждал.

Там была какая то проблема. Да пофиг уже все же работает! Меня этот курсач уже заманал!!! Я его уже хрен знает сколько делаю... Прямо самая сложна хрень какую я в жизни писал... У меня даже диплом в 100 раз проще чем это.

**Comment by mayorovp** [comment]
То ли еще будет, когда на работу пойдете :)

**Comment by DarkByte2015** [comment]
Сдал на отлично! Правда препод все таки ухитрился мне обрушить сервер и сначала не хотел ставить отл, но потом все таки согласился. :D
